// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3PjDruHcOPJBvwP0qIiuye3CsICeEKqo',
    appId: '1:821467863605:web:e5a79d6e3b5b95e222ef7c',
    messagingSenderId: '821467863605',
    projectId: 'ecommerce-60722',
    authDomain: 'ecommerce-60722.firebaseapp.com',
    storageBucket: 'ecommerce-60722.appspot.com',
    measurementId: 'G-9G1FT137P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt3ls5qA2oan0nodw8CCvAX1Z_aa6UyvQ',
    appId: '1:821467863605:android:a8e9b372900f01a422ef7c',
    messagingSenderId: '821467863605',
    projectId: 'ecommerce-60722',
    storageBucket: 'ecommerce-60722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoZvgfi9cUQzEAf4qS3lUVQ6fKvS2pfW4',
    appId: '1:821467863605:ios:8873990320948c7322ef7c',
    messagingSenderId: '821467863605',
    projectId: 'ecommerce-60722',
    storageBucket: 'ecommerce-60722.appspot.com',
    androidClientId: '821467863605-ktan97q8i08pod0kldli5htjel72corb.apps.googleusercontent.com',
    iosClientId: '821467863605-2e3js4pglitru6e4saqa41lnf3qmm6oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionApp',
  );
}
